//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTTV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuongMua
    {
        public int Id_LuongMua { get; set; }
        public int Id_Tram { get; set; }
        public int Id_KhuVuc { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<decimal> NhietDo { get; set; }
        public Nullable<decimal> DoAm { get; set; }
        public Nullable<decimal> Mua { get; set; }
        public Nullable<decimal> MucNuoc { get; set; }
        public Nullable<decimal> Nguon { get; set; }
    
        public virtual Tram Tram { get; set; }
    }
}
