//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTTV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public int Id_NguoiDung { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
