//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTTV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tram
    {
        public Tram()
        {
            this.LuongMuas = new HashSet<LuongMua>();
        }
    
        public int Id_Tram { get; set; }
        public string TenTram { get; set; }
    
        public virtual ICollection<LuongMua> LuongMuas { get; set; }
    }
}
